### PR TITLE
Add win32 test harness

### PR DESCRIPTION
**Pull request by timsneath**
- Adds some tests for FFI. 
- Also updates the `pub get` command to use the new 1.22+ `flutter pub` command.

### CODE REVIEW

**Comment by goderbauer** [comment]
Looks like this is failing on windows.

**Comment by timsneath** [comment]
Yeah, I need to take a look and figure out what's going wrong on Travis, because this works perfectly on GitHub Actions: https://github.com/timsneath/win32/actions/runs/601692729

Turns out that I ran out of time yesterday for some reason :)

**Comment by goderbauer** [comment]
@timsneath Do you still have plans to come back to this one any time soon? Otherwise, can we close it to get it off the queue? :)

**Comment by timsneath** [comment]
Oh -- thanks for the ping! I'll close it for now and I can always reopen when I have time.

**Pull request closed without merging**
