### PR TITLE
Update zulip to use Color{,Swatch} asserts that tolerate float errors

### PR DESCRIPTION
**Pull request by chrisbobbe**
Fixes flutter/flutter#155113.

This pulls in:
  https://github.com/zulip/zulip-flutter/commit/cdbe14122
  https://github.com/zulip/zulip-flutter/pull/949

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md

### CODE REVIEW

**Review by gnprice — APPROVED** [review]
Thanks! LGTM assuming tests pass.

@gaaclarke FYI

**Comment by gaaclarke** [comment]
A lot of people are off at a conference, but I'll try to get it relanded tomorrow.  Thanks.

**Comment by gnprice** [comment]
Cool, sounds good.

If you hit "approve" on this PR, then we can land this flutter/tests update to prepare for that.

(I guess the GitHub UI is offering to let me merge it already. But I think the intended policy is that PRs here require two flutter-hackers approvals to merge, just like in the main Flutter repos, and we just haven't set things up to enforce that here.)

**Review by gaaclarke — APPROVED** [review]

**Comment by gnprice** [comment]
Let's see if the autosubmit bot is active here… yep!

**Pull request merged**
