### PR TITLE
Run `dart fix --apply` before creating SKPs

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
OOO fun! This may not work completely in every case (some dart fixes require some follow up from the user after the transform), but this looks really neat!

In those cases I guess we would just follow breaking change protocol. Should we let the test authors know we are including this before landing?

**Comment by Hixie** [comment]
This is just about the SKP generator, doing this before we run the customer testing shard landed a while ago.

**Comment by Piinks** [comment]
> This is just about the SKP generator, doing this before we run the customer testing shard landed a while ago.

Oh! I did not realize! Sweet!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Comment by Hixie** [comment]
Yup, the net result of which is that if you create a dartfix, you can side-step the breaking change process because it no longer breaks the customer tests. :-)

**Pull request merged**
