### PR TITLE
Update flutter_cocoon test

### PR DESCRIPTION
**Pull request by TahaTesser**
Unblocks https://github.com/flutter/flutter/pull/155072

This updates flutter_cocoon test so the https://github.com/flutter/flutter/pull/155072 can test the latest flutter_cocoon after https://github.com/flutter/cocoon/pull/3901 fix.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md

### CODE REVIEW

**Review by parlough — APPROVED** [review]

**Comment by TahaTesser** [comment]
Looks like other customer tests are failing. Might not be related to this PR.

**Comment by TahaTesser** [comment]
it looks like `flutter_cocoon` has bunch of other failures. Do we fix them all to update customer_test commit?

**Comment by Piinks** [comment]
Hmm I do not know why this is failing. Will look in flutter/cocoon.

**Comment by Piinks** [comment]
https://github.com/flutter/cocoon/pull/3953 should unblock this, but we'll need to update the hash for flutter/cocoon here.

**Review by parlough — APPROVED** [review]
I updated the commit ref to include Kate's other fixes.

Thanks!

**Comment by Piinks** [comment]
Thanks @parlough!!

**Review by Piinks — APPROVED** [review]
LGTM

**Pull request merged**
