### PR TITLE
Bump flutter_devtools to c8af1c0cdb77142f7ad0236b074e7c068498da0b

### PR DESCRIPTION
**Pull request by srawlins**
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by bartekpacia** [comment]
Hi, I was about to make the same PR but for a newer commit: https://github.com/flutter/devtools/commit/14aa44eb97a504a94848ac7908a481733557e718

This is needed for unblocking https://github.com/flutter/flutter/pull/138331. [More context on Discord](https://discord.com/channels/608014603317936148/1179200000136319037/1181990695662256260).

I can make a separate PR but I though I'll try asking:)

**Review by bartekpacia — APPROVED** [review]

**Comment by srawlins** [comment]
I just bumped to the commit after yours :)

**Comment by bartekpacia** [comment]
awesome! Thanks (:

Could this be merged or do you prefer to wait until Monday?

**Comment by srawlins** [comment]
I'm happy to merge whenever. I just need approval.

**Review by bartekpacia — APPROVED** [review]
You got mine

**Review by parlough — APPROVED** [review]

**Comment by bartekpacia** [comment]
[My framework PR](https://github.com/flutter/flutter/pull/138331)'s CI is not picking up this change. Any ideas why?

**Pull request merged**
