### PR TITLE
Delete super_editor.test

### PR DESCRIPTION
**Pull request by dnfield**
These tests has never passed, and have historically suffered from https://github.com/superlistapp/super_editor/issues/728

We should not have the run as part of the suite until they are passing.

@matthew-carroll FYI

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by matthew-carroll** [comment]
What do you mean they've never passed?

**Comment by dnfield** [comment]
@matthew-carroll - I mean that the scripts always reported success, but the tests actually failed if you closely read the output. This is a frequent source of confusion now, since the scripts report success but the tests report failure.

I am fully supportive of adding these back,b ut we should add them back in a passing state.

**Comment by dnfield** [comment]
Looking back, it seems like there was a time where this script was passing, so I misspoke :)

But it seems like they may have been failing for a long time. Because they did not report failure in a way detectable to CI, it's hard to tell when that started, and a frequent source of confusion. So for now we should just disable them and look to re-enable them separately.

**Comment by dnfield** [comment]
Looks like they probably started failing with https://github.com/flutter/flutter/pull/105407

**Comment by dnfield** [comment]
The tests were added July 13th, the patch causing them to fail was merged August 5th. They have been silently failing for most of the time they've been around. It would be very difficult right now to go back and revert all of the patches that have further contributed to failures. My proposal is to instead patch super_editor forward and re-add it here.

**Comment by dnfield** [comment]
And I'm deleting rather than just waiting for a fix forward because this has more than once caused confusion for gardeners trying to root cause unrelated failures - you see these errors when you go looking in the log and if you're not already familiar you have to track down why it's failing only to find out there's some _other_ failure that's actually blocking the tree.

**Pull request merged**
