### PR TITLE
Update flutter_reactive_ble to support Dart 3

### PR DESCRIPTION
**Pull request by CaseyHillers**
https://github.com/flutter/flutter/issues/116671

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by CaseyHillers** [comment]
@remonh87 FYI

**Review by zanderso — DISMISSED** [review]

**Comment by CaseyHillers** [comment]
A few of these tests seem to be failing on:

```
ERROR: The directory ., which was specified as an update directory, does not contain a "pubspec.yaml" file.
```

This project was refactored into a few smaller packages (for federated plugins). I'll update the `.` to the various locations

**Comment by jason-simmons** [comment]
The `flutter analyze` and `flutter test` commands need to be run separately from the `packages/flutter_reactive_ble`, `packages/reactive_ble_mobile`, and `packages/reactive_ble_platform_interface` directories.

AFAIK the customer test registry format does not have a way to declare this.  You may need to add a script to the third party repository that runs the tests in each package.

Also, roll the checkout to https://github.com/PhilipsHue/flutter_reactive_ble/commit/16747c45f7e262c1829bcc1d028d2d7cb89c1493 to get the latest package versions.

**Comment by zanderso** [comment]
Another approach might be adding the ability to specify a working directory for the `test=` lines. Could parse it out here: https://github.com/flutter/flutter/blob/master/dev/customer_testing/lib/customer_test.dart#L29, but adding a script to the customer repo is probably simpler.

**Comment by Hixie** [comment]
Generally we just create a shell script and batch file in the target repo and run the commands there.

**Comment by Hixie** [comment]
(For example, see the `flutter_packages.test` file.)

**Comment by CaseyHillers** [comment]
Closing due to https://github.com/flutter/tests/pull/184

**Pull request closed without merging**
