### PR TITLE
Updated super_editor to report failure when tests fail

### PR DESCRIPTION
**Pull request by matthew-carroll**
Updated super_editor to report failure when tests fail

### CODE REVIEW

**Comment by Hixie** [comment]
Looks like there's a test failure.

**Comment by matthew-carroll** [comment]
Yeah, it looks like a breaking change was introduced. Do you know the expected date for the next stable rollout? We have some super_editor clients actively integrating changes that we're making. I can't force them onto `main` right now for Flutter.

**Comment by Hixie** [comment]
Not sure exactly but we do releases every 3 months or so in general. Last stable was in May, for what it's worth.

**Comment by matthew-carroll** [comment]
Ok. I'll try to remember to submit a new PR whenever the breaking change comes to stable.

**Pull request closed without merging**
