### PR TITLE
Update flutter_devtools.test

### PR DESCRIPTION
**Pull request by zanderso**
To pick up https://github.com/flutter/devtools/pull/6818, to unblock Dart -> Flutter rolls.

### CODE REVIEW

**Review by eyebrowsoffire — APPROVED** [review]
LGTM!

**Comment by zanderso** [comment]
Hi @DanTup, I'm trying to roll flutter/devtools into flutter/tests, but it looks like there's an issue with the change here https://github.com/flutter/devtools/pull/6776, which is causing `tools/bin/devtools_tool` to fail to find the Dart SDK when invoked from `tools/ci/setup.sh`. It looks like it's only failing on Linux, so maybe something related to the way that (environment) variables are set from the shell scripts?

**Comment by DanTup** [comment]
I'm not sure why things wouldn't be consistent across platforms, but do you know where the Flutter SDK is being set up in this case? It looks like flutter_customer_tests/setup.sh assumes Flutter already exists but I'm not sure where it's set up.

In the PR you linked, we made devtools_tool always expect to use a Flutter SDK from the `tool/flutter-sdk` folder (whereas before, we could pick it up from `PATH` too). The reason for this was that DevTools is pinning specific versions of Flutter and we didn't want to accidentally get a different version from a users PATH.

However, it's not clear to me if the tests here want to always run with the latest one (in which case we may need a way to override this, or we need it tbe cloned or symlinked into `tool/flutter-sdk`).

(cc @kenzieschmoll in case she has any opinions/preferences on how this is solved)

**Comment by zanderso** [comment]
The purpose of the customer tests is to test against tip-of-tree Flutter, to ensure that changes to Flutter don't unintentionally break those tests. So in that scenario, running against the Flutter SDK from the environment rather that one pinned to an earlier version would be working as intended.

**Comment by zanderso** [comment]
@DanTup, offline @jacob314 recommended we revert at https://github.com/flutter/devtools/pull/6820 to unblock the rolls.

**Comment by DanTup** [comment]
Makes sense to me - I'll tweak it to support this (perhaps by adding an env variable to allow forcing use of Flutter from `PATH`). Thanks!

**Review by eyebrowsoffire — APPROVED** [review]
LGTM!

**Pull request merged**
