### PR TITLE
Update rainbowmonkey.test

### PR DESCRIPTION
**Pull request by pedromassango**
This PR is a follow up of https://github.com/flutter/flutter/pull/61648 to make tests of that PR to pass. 

I've just updated a customer's tests to point to the latest commit introduced by https://github.com/jocosocial/rainbowmonkey/pull/329.

### CODE REVIEW

**Comment by pedromassango** [comment]
Cc: @Hixie

**Comment by Hixie** [comment]
I don't see the failure in the logs, weird.

LGTM once we have fixed whatever is causing the failure...

**Comment by Hixie** [comment]
Some sort of problem with the gallery tests?:
```
Processing ./registry/flutter_gallery.test...
Created temporary directory: /tmp/flutter_customer_testing.flutter_gallery.AYIVVE
>> git -c core.longPaths=true clone https://github.com/flutter/gallery.git tests
| Cloning into 'tests'...
>> git -c core.longPaths=true -C tests checkout b22eb190a66a5fb61fcafcc5fa66723f37e17723
| fatal: reference is not a tree: b22eb190a66a5fb61fcafcc5fa66723f37e17723
ERROR: Failed to fetch repository.
Contacts: raboughanem@google.com, perc@google.com
Deleting temporary directory...
```

**Comment by pedromassango** [comment]
Thanks. I will keep my eyes on this.

**Comment by chunhtai** [comment]
@pedromassango Please rebased your branch off the master branch to fix the test failure

**Pull request merged**
