### PR TITLE
Update flutter_svg.test

### PR DESCRIPTION
**Pull request by dnfield**

### CODE REVIEW

**Comment by GaryQian** [comment]
Looks like there are a few presubmit failures, but otherwise LGTM

**Comment by Hixie** [comment]
LGTM and ok to land on red, I'm fixing the precommit issues in a separate PR

**Comment by Hixie** [comment]
LGTM and ok to land on red, I'm fixing the precommit issues in a separate PR

**Comment by dnfield** [comment]
Needs an approved review - comment with LGTM isn't good enough

**Pull request merged**
