### PR TITLE
Add `macos_ui` to customer testing

### PR DESCRIPTION
**Pull request by GroovinChip**
This PR adds [`macos_ui`](https://pub.dev/packages/macos_ui) to the registry of customer tests.

Closes https://github.com/flutter/flutter/issues/119940

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

N/A

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing. (I ran the customer tests locally per the tests repo `README`)

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by GroovinChip** [comment]
CC @Piinks :)

**Comment by GroovinChip** [comment]
@Piinks That's really odd because when I run `dart fix --apply` locally it shows nothing to fix. And my linter shows nothing as well

**Comment by TahaTesser** [comment]
> EDIT: wait, could this be because the tests are run against the master channel? Because I work off of stable :/

That's likely the reason.

**Comment by Piinks** [comment]
Yes, @TahaTesser is right. These tests are run against the master branch. That is how we are able to test every change that is staged for the master branch to prevent breaking the registered test suite.

**Comment by GroovinChip** [comment]
Okay. I guess I'm going to need to set up a branch that runs on master, then.

**Comment by GroovinChip** [comment]
Alright, I've created a `customer_testing` branch in `macos_ui` that is based on Flutter's master channel, and updated `macos_ui.test` to reflect the latest commit there. 

That said, the tests are failing on my machine which I suspect is due to my use of FVM for my `customer_testing` branch. I suspect it is because I've configured only that branch to be on master, and the rest of my machine is on stable. Hopefully they'll all pass on this PR, since the environment is appropriate; otherwise, I suspect I'll need to add a "fetch" line that switches branches after the repo gets cloned.

**Comment by GroovinChip** [comment]
Looks like the 2 checks that failed did so because they timed out. Can we get those to be rerun?

**Comment by Piinks** [comment]
I have rerun them and they are still failing. Can you try rebasing?

**Comment by GroovinChip** [comment]
I'm up to date with upstream, not sure why the tests still fail for Linux & Windows...I checked my tests and I don't have any that call the small amounts of native code in the plugin. Perhaps it might be best if I configure the tests to only run on macOS?

**Comment by Piinks** [comment]
Sometimes our CI just needs a kick, and rebasing or pushing a new commit does that.

> Perhaps it might be best if I configure the tests to only run on macOS?

If the macos_ui tests are passing, then why would you want to omit them?

**Comment by GroovinChip** [comment]
> If the macos_ui tests are passing, then why would you want to omit them?

I'm referring to configuring the platform that the CI runs the tests on. The template talks about being able to choose macOS, Windows, or Linux, or leave it as default, which is all three

**Comment by GroovinChip** [comment]
@Piinks all tests are green 🎉

**Review by Piinks — APPROVED** [review]
LGTM!

**Comment by Piinks** [comment]
This just needs a second approval, seeking one now.

**Review by loic-sharma — APPROVED** [review]

**Pull request merged**
