### PR TITLE
Add the flutter/plugins tests

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
cc @collinjackson it looks like this is going to be less easy than just running the tests, because they take such a long time to run. :-(

**Comment by collinjackson** [comment]
> cc @collinjackson it looks like this is going to be less easy than just running the tests, because they take such a long time to run. :-(

Maybe just start with `./script/incremental_build.sh analyze` which should catch the breaking changes.

**Comment by Hixie** [comment]
I think the right thing here is just to run the tests as a new shard.

**Comment by Hixie** [comment]
(on flutter/flutter itself)

**Pull request closed without merging**
