### PR TITLE
[WIP] Adding devrel samples

### PR DESCRIPTION
**Pull request by RedBrogdon**
This is temporarily using a private fork of the devrel samples which already has the scripts that will be added in this PR:

https://github.com/flutter/samples/pull/122

I'm assuming there's some CI setup here that'll run my new registry entry, which is why I'm adding this now. I'll update it to the correct repo and commit before landing.

### CODE REVIEW

**Comment by RedBrogdon** [comment]
@Hixie I'm not sure how to make both Windows and Linux happy here. Windows doesn't want a `./` preceding the script name, and Linux does.

**Comment by RedBrogdon** [comment]
@hixie I'm at SFO now, about to be OOO until 8/6. I've merged the PR with the test script/batch file in flutter/samples and updated the test registry file here to point to that commit within the repo.

If this passes the CI checks, it can be landed. If not, feel free to either land it and then update it however is necessary, or (if you don't mind waiting week or so) let me know what I can do to get it finished up.

**Comment by goderbauer** [comment]
@RedBrogdon Can you rebase this to the latest master and push to this branch to trigger cirrus again?

**Comment by goderbauer** [comment]
FYI: https://github.com/flutter/tests/pull/23 is adding the Flutter Gallery from the samples repository.

**Comment by goderbauer** [comment]
I am going to close this for now. Please feel free to reopen when you have the time to work on this again :)

**Pull request closed without merging**
