### PR TITLE
Re-enabled super_editor tests

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

Re-enables the `super_editor` tests now that it has been migrated to use `KeyEvent` instead of `RawKeyEvent`.

## Related Issues
 - https://github.com/flutter/flutter/issues/136419

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@gspencergoog looks like we've got some failing tests

**Comment by gspencergoog** [comment]
Yep, it looks like there's a bug in `dart fix --apply` that the code is tweaking: I filed an issue: https://github.com/dart-lang/sdk/issues/54190

While we wait for a fix, would it be OK if I removed some unused parameters from your `content_layers_test.dart` file? I'll send you a PR.

**Comment by matthew-carroll** [comment]
@gspencergoog I'll need to see what you'd like to remove. Content layers is an extremely fragile hack that's critical to super_editor, but if there are truly some unused and irrelevant code then I can look into deleting it.

**Comment by gspencergoog** [comment]
OK, I sent you the PR: https://github.com/superlistapp/super_editor/pull/1630

**Pull request merged**
