### PR TITLE
Evict DanTup_tiler.test due to flakes

### PR DESCRIPTION
**Pull request by tvolkert**
Experiencing the following flake:

```
| ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
| The following TestFailure object was thrown running a test:
|   Expected: one widget whose rasterized image matches golden image
| "test-maps/orientation/isometric_windows.png"
|   Actual: ?:<exactly one widget with type "RepaintBoundary" (ignoring offstage widgets):
| RepaintBoundary(renderObject: RenderRepaintBoundary#5401b)>
|    Which: does not match
```

### CODE REVIEW

**Comment by Hixie** [comment]
cc @dantup

**Comment by DanTup** [comment]
I've updated these a few times due to them failing (I believe there were anti-aliasing differences - @gspencergoog may have been looking at?). I'm happy to keep regenerating them, but I don't know whether that's the right thing to do (I'm not sure if these subtle changes are bugs, or whether my tests are somehow affected more than others).

**Comment by tvolkert** [comment]
Not sure - it seems to always be `isometric_windows.png` that's affected.  We should add these back once we figure out why they're flaky - or just exclude that one test and add back the rest.

**Comment by DanTup** [comment]
There are `isometric_windows.png` in a few different folders, but it does seem to always be them - they do all have weird canvas transforms in them - I'm not sure if that's related.

I've updated them again for current master:

https://github.com/DanTup/tiler/commit/254e93ccfd3a316a562dd3b238a249f985ae0c10

Weirdly, they're now passing on stable, dev and master:

https://travis-ci.org/DanTup/tiler/builds/561457098

So I wonder if the aliasing is back to what it was? I'll leave it to you if you think it's worth putting back in though.

**Comment by tvolkert** [comment]
@DanTup if the test aren't flaky, then by all means add them back.  Have you tried `--repeat=100` on Windows?

**Comment by DanTup** [comment]
I haven't yet - I thought they were consistently failing due to the AA changes (this is what I saw with the previous issues - changing which Flutter version I used resulted in different images). If in this case they were flaky with the same version, it might be something else (though something that complicated things previously, is that the PR branches will run the version branched from, then after merging to master it'll use the latest there - so passing in the PR then failing in master doesn't necessarily mean it's flaky).

I'll try running them a load of times when next at my PC and see how it goes.

**Comment by Hixie** [comment]
fwiw the precommit tests run the tests 15 times per platform

**Comment by DanTup** [comment]
I just ran the tests 200 times and they passed every time. Then I realised I hadn't even updated the hash in the registry, so I did some more digging and found that the current code is cloning the Tiler repo, but when it's setting up the sub-repo, it's always getting the latest version of it and not the version that's specified by the parent repo.

I think this could've added to making it look flaky, because re-running the same PR could have different results for the same code if I'd pushed another change to the sub-repo.

I'm just trying to figure out why this happens (the commands in the registry seem sensible from reading the docs, but it definitely gets the wrong hash - it's in the output!). I'll also try to verify whether the latest goldens I have now are back the same as they originally were (before we say any failures), which may suggest it was a temporary "break" in Flutter (which I re-generated Goldens for, but was since fixed).

**Comment by DanTup** [comment]
Ok, the issue seemed to be the `--remote` when updating the sub-repo - that caused it to fetch latest from the remote, not checkout the version specified by the container.

I also rolled back to before any of the recent golden updates, and they pass on Flutter master. This makes me think it was a temporary issue in Flutter (with the aliasing) that has since returned to its original state, but my re-generation of the goldens resulted in it failing again.

I'll open a PR to put these back (minus the `--remote`) and we can see how it goes. I think there's value in these, since the original breakages here were seen elsewhere (golden tests failing due to AA), so assuming we want to catch that sort of thing, I think they did their job :-)

**Comment by tvolkert** [comment]
SGTM - thanks for investigating.

**Pull request merged**
