### PR TITLE
add flutter_rfb

### PR DESCRIPTION
**Pull request by Goddchen**
* Tests of the `flutter_rfb` package, mainly some byte level manipulations.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [X] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by Hixie** [comment]
Looks great! I'm rerunning the tests to make sure and then we'll add the tests! Thanks!

**Review by Hixie — APPROVED** [review]
LGTM

**Comment by Goddchen** [comment]
@Hixie Can you give me some insights on this failing test? I'm not sure where I should start to investigate. It's timing out... But why only on windows?

**Review by werainkhatri — APPROVED** [review]
RSLGTM

**Comment by Goddchen** [comment]
@Hixie @werainkhatri issue with the windows runner still seems to persist 🙁 Is there anything I can do on my end?

**Comment by Hixie** [comment]
> @Hixie @werainkhatri issue with the windows runner still seems to persist 🙁 Is there anything I can do on my end?

Sorry for the lack of updates. I was adjusting the tests in the background so that they would stop timing out, but it takes a little while for all the changes to fall into place because there's multiple repos involved. Looks like it's all resolved now!

**Comment by Goddchen** [comment]
@Hixie thank you so much

**Comment by Hixie** [comment]
thank _you_! hopefully having these packages in the tests registry means we never break you again!

**Pull request merged**
