### PR TITLE
Rename DanTup_tiler.test to DanTup_tiler.test.disabled

### PR DESCRIPTION
**Pull request by zanderso**
The pixel tests in the tiler suite are experiencing the same failure as is described in https://github.com/flutter/flutter/issues/149934

cc @DanTup 

```
| ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
| The following assertion was thrown while running async test code:
| Golden "test-maps/geometry/orthogonal_macos_arm.png": Pixel test failed, 0.00%, 8px diff detected.
| Failure feedback can be found at
| /Volumes/Work/s/w/ir/x/t/flutter_customer_testing.DanTup_tiler.GmgOoy/tests/test/failures
|
| When the exception was thrown, this was the stack:
| #0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:106:5)
| <asynchronous suspension>
| #1      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:118:32)
| <asynchronous suspension>
| <asynchronous suspension>
| #3      _expect.<anonymous closure> (package:matcher/src/expect/expect.dart:123:26)
| <asynchronous suspension>
| <asynchronous suspension>
| #5      expectLater.<anonymous closure> (package:flutter_test/src/widget_tester.dart:512:24)
| <asynchronous suspension>
| #6      expectMapRender (file:///Volumes/Work/s/w/ir/x/t/flutter_customer_testing.DanTup_tiler.GmgOoy/tests/test/utils.dart:43:5)
| <asynchronous suspension>
| #7      testMapRender.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/t/flutter_customer_testing.DanTup_tiler.GmgOoy/tests/test/utils.dart:20:5)
| <asynchronous suspension>
| #8      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
| <asynchronous suspension>
| #9      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1025:5)
| <asynchronous suspension>
| <asynchronous suspension>
| (elided 3 frames from dart:async and package:stack_trace)
|
| The exception was caught asynchronously.
| ════════════════════════════════════════════════════════════════════════════════════════════════════
|
| 00:05 +10 -1: geometry/orthogonal [E]
|   Test failed. See exception logs above.
|   The test description was: geometry/orthogonal
|
|
| To run this test again: /Volumes/Work/s/w/ir/x/w/flutter/bin/cache/dart-sdk/bin/dart test /Volumes/Work/s/w/ir/x/t/flutter_customer_testing.DanTup_tiler.GmgOoy/tests/test/render_test.dart -p vm --plain-name 'geometry/orthogonal'
```

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by matanlurey — APPROVED** [review]

**Comment by DanTup** [comment]
@zanderso [I updated the goldens](https://github.com/DanTup/tiler/commit/d100013919d9c5580feec61b40f19e581861ed7b) in that repo for the latest Flutter. I don't know how useful these tests are (I'm not developing/maintaining Tiler besides fixing these tests).. If you think they're useful I can send a PR to re-enable this and update the hash, otherwise they could be removed.

**Comment by DanTup** [comment]
@zanderso any opinions on the above? Should I file a PR to re-enable these now they've updated, or should we remove it? I don't know if I'm providing any tests the framework doesn't already have (I think so far all cases of failures here have been known/expected changes and result in this dance). I'm happy to maintain the tests if there's some value in them though.

**Comment by zanderso** [comment]
Are there any tests aside from the golden tests in the tiler suite? The golden tests are probably not high-value, and we should delete those. If there are non-golden tests for tiler, then they probably have a better cost/benefit trade-off, and we should keep them.

**Comment by DanTup** [comment]
Nope, no other tests. The tests were all specifically for rendering images/sprites/shapes onto a canvas. If those are things are already well-tested by Flutter and there are enough other projects here to ensure we feel the pain users feel when the goldens change in breaking ways, I agree it probably makes sense to remove them. I'll open a PR.

**Pull request merged**
