### PR TITLE
Update registry with commit hashes for test repos with button updates

### PR DESCRIPTION
**Pull request by HansMuller**
Update the registry to pull in versions of the test repos that have been updated per flutter/flutter#59702.

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM as long as tests are passing

**Comment by dnfield** [comment]
Looks like there are some merge conflicts to fix

**Comment by HansMuller** [comment]
I fixed the merge issues and the tests pass locally. Hopefully the bots will be happy with the changes too :-).

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
