### PR TITLE
update contact for reactive ble test

### PR DESCRIPTION
**Pull request by remonh87**

### CODE REVIEW

**Comment by remonh87** [comment]
@googlebot I signed it!

**Comment by goderbauer** [comment]
@miguelcmedeiros You originally added this project. Can you acknowledge that this change of contact is ok with you?

**Review by miguelcmedeiros — APPROVED** [review]
@goderbauer, I can confirm that Remon is one of the main maintainers of `flutter_reactive_ble`
🚀

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
