### PR TITLE
add dart_rfb

### PR DESCRIPTION
**Pull request by Goddchen**
Add tests from `dart_rfb` package. Mostly byte manipulation, `fromBytes(...)`, `toBytes()`, etc stuff.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [X] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Review by Hixie — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Thanks!

**Comment by Goddchen** [comment]
@Hixie Can you give me some insights on this failing test? I'm not sure where I should start to investigate. It's timing out... But why only on windows?

**Comment by Hixie** [comment]
not your fault, one of the other tests is taking a long time and the test times out. we'll fix it.

**Review by werainkhatri — APPROVED** [review]
RSLGTM

**Pull request merged**
